data_ingestion:
  local_data_path: "data/raw/hotel_reservations.csv"
  s3_bucket: "mlops-project-data-251130"
  s3_prefix: "hotel_reservation/"
  aws_profile: "default"
  region: "us-west-2"

data_processing:
  processed_data_path: "data/processed/hotel_reservations_processed.csv"
  processed_train_data_path: "data/processed/hotel_reservations_train.csv"
  processed_test_data_path: "data/processed/hotel_reservations_test.csv"

model_training:
  categorical_columns:
    - type_of_meal_plan
    - required_car_parking_space
    - room_type_reserved
    - market_segment_type
    - repeated_guest
    - booking_status
  numerical_columns:
    - no_of_adults
    - no_of_children
    - no_of_weekend_nights
    - no_of_week_nights
    - lead_time
    - arrival_year
    - arrival_month
    - arrival_date
    - no_of_previous_cancellations
    - no_of_previous_bookings_not_canceled
    - avg_price_per_room
    - no_of_special_requests
  target_column: "is_canceled"